name: Icon Data for Ku9

on:
  workflow_dispatch:
  repository_dispatch:
    types: [icon4ku9]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run script
        run: python ku9.py

      - name: Check for changes
        id: changes
        run: |
          git add ku9/epg_data.json ku9/alias.json ku9/icon.zip
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update EPG and alias data"
          git push

      - name: Repository Dispatch
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: taksssss/iptv-tool
          event-type: synciconlist
